### ISSUE TITLE
Not working with Office 2021 Pro Plus 

### ISSUE THREAD

**Issue by mikeloeven** [Ourselp/KeepOutlookRunning#6]
AddIn is no longer working after upgrading to Office 2021 Pro Plus. Getting an error that the DLL is not a valid office plugin. I can confirm I already have the prereq Runtimes installed and was using this with my previous installation of outlook 2013 without issue. Should be a simple version update to support the most recent outlook

**Comment by kamilmirza** [comment]
+1

**Comment by BearTheMad** [comment]
My office version is 2021 Pro Plus too. And it works after i install both Microsoft Visual C++ 2010 SP1 32bit and 64bit

**Comment by arafth** [comment]
Not working with Windows 11

**Comment by BearTheMad** [comment]
> Not working with Windows 11

Sorry, my office version is 2019 Pro Plus, and it works for me last month , but now it doesn't work again.

**Comment by bersbersbers** [comment]
> Getting an error that the DLL is not a valid office plugin

Got that when I tried a 64-bit dll on a 32-bit installation on Outlook. Fixed for me by using a 32-bit dll.

Neverthess, still not working for me due to 

> "Not loaded. Certificate of signed and load at startup COM Add-in is not in trusted source List."

**Comment by Huaweidev** [comment]
Can load the KeepOutlookRunning-64bit.dll to Microsoft Office 2021 LTSC enhanced version.

**Comment by mikeloeven** [comment]
So figured out the problem I am a idiot. Basically when I had a problem loading the addin I tried to download a fresh copy of the DLL so what ended up happening Is I had clicked on the 32 bit by mistake but since I was overwriting the old file I ended up with the wrong DLL the 32 bit named like the 64 bit one. You can mark this as resolved

**Comment by weigaow** [comment]
> Can load the KeepOutlookRunning-64bit.dll to Microsoft Office 2021 LTSC enhanced version.

这个问题您解决了吗？

**Comment by Huaweidev** [comment]
> > Can load the KeepOutlookRunning-64bit.dll to Microsoft Office 2021 LTSC enhanced version.
> 
> 这个问题您解决了吗？

No, I gave up on that need, it wasn't important to me.
